---
name: Check_status

on:
  workflow_call:
    inputs:
      owner:
        required: false
        default: ome
        type: string
      repo:
        required: true
        default: openmicroscopy
        type: string
      branch:
        required: false
        default: main
        type: string

jobs:
  check:
    name: Check status
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check status of the last run of given repository against the specified branch
        id: check_status
        run: |
          output=$(gh run list --jq ' .[] |  select(.status | contains("completed")) | select(.headBranch | contains("${{ inputs.branch }}"))' --json headBranch,conclusion,status,createdAt,url  -R $OWNER/$REPO --limit 1)
          status=fail
          if [ -n "$output" ]; then
              status=$(echo "$output" | jq -r '.conclusion')
          fi
          if [[ "$status" != "success" ]]; then
             exit 1
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ inputs.owner }}
          REPO: ${{ inputs.repo }}
